# Generated by Django 4.0.2 on 2022-02-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=240)),
                ('favorite_messenger', models.CharField(blank=True, choices=[('VK', 'vk'), ('WA', 'WhatsApp'), ('VB', 'Viber'), ('TG', 'Telegram'), ('IG', 'Instagram')], max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_born', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_site', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_update_status', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('W', 'на рассмотрении'), ('C', 'на согласовании'), ('P', 'создание прототипа'), ('D', 'создание дизайна'), ('L', 'верстка'), ('B', 'программирование'), ('S', 'деплой'), ('F', 'выполнен')], default='W', max_length=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.customer')),
                ('type_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.typesite')),
            ],
        ),
    ]
