# Generated by Django 4.0.2 on 2022-07-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=240)),
                ('type_site', models.CharField(choices=[('L', 'Лединг'), ('V', 'сайт-визитка'), ('C', 'корпоративный сайт'), ('N', 'неопределен')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('price', models.IntegerField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'тип сайта',
                'verbose_name_plural': 'типы сайтов',
            },
        ),
    ]
