# Generated by Django 4.0.2 on 2022-07-14 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_delete_typesite_order_time_create'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'заказ', 'verbose_name_plural': 'заказы'},
        ),
    ]
